### ISSUE TITLE
Standalone CMake script

### ISSUE THREAD

**Issue by curiousdannii** [tads-intfic/tads-runner#1]
This repository has inherited the CMake script from Garglk, which obviously won't work outside of it. It would be good if it worked stand alone, ideally for both a console/curses port, and the Glk port.

Or maybe two CMake scripts would be best, one for each port. That's probably more sensible.

**Comment by curiousdannii** [comment]
We could use some git magic to move all the Glk "os" files to a glk folder and keep their history. If we do that now it wouldn't be too disruptive, which it would be later. But there are internal paths which would no longer work at any of those commits. Pros and cons on both sides.

**Comment by realnc** [comment]
I don't think there should be any build files in this repo. This isn't an interpreter, after all. It's just the Tads base code, as used by the various terps out there.

**Comment by curiousdannii** [comment]
Maybe. But for the Glk port, if it's like Glulxe then there's little reason to not provide a build script of some sort, as it should only need you to point it to the Glk lib's location in order for you to build it. Obviously the more involved interpreters shouldn't include their stuff here, but I'd like for the Glk lib to become even more generic than it is now, so that it can safely be built against all Glk libs, not just Garglk (though with less functionality of course.)

**Comment by realnc** [comment]
In that case just a normal commit moving files to their own directory should be totally fine, I think.

**Comment by curiousdannii** [comment]
I moved the glk files to a glk folder, rewriting their history. This should be the last history change, we shouldn't need any more.
