### ISSUE TITLE
Use grid windows when style is OS_BANNER_STYLE_TAB_ALIGN

### ISSUE THREAD

**Issue by curiousdannii** [tads-intfic/tads-runner#10]
In the forum @realnc [explained](https://intfiction.org/t/how-are-the-tads-menus-generated/53555/7?u=dannii)

> The adv3 menu system doesn’t create text grid banners. Only normal ones. Some have the OS_BANNER_STYLE_TAB_ALIGN set. Gargoyle switches to a fixed-width font for banners that have that flag set.

The problem with doing this is that when it asks for the banner's width, it measures it in proportional width characters, and if the fixed width font is wider, then it prints too much for each line. Gargoyle doesn't have this problem, because it measures all windows in fixed width fonts (technically against the Glk spec.) @angstsmurf [said](https://github.com/curiousdannii/emglken/issues/22#issuecomment-981622420) that Spatterlight has a custom function to calculate the width.

Considering that we're already setting all the Glk styles to fixed width (well all the ones osglkban.c uses) when the style is OS_BANNER_STYLE_TAB_ALIGN, it seems to me that the intention is for the whole window to use fixed width fonts. If that's the case, then why not just use a grid window in the first place? Then we wouldn't need any work arounds like Spatterlight has; all the styles would be guaranteed to be fixed width, and the Glk width functions would safely return the true width.

See also https://github.com/curiousdannii/emglken/issues/22

**Comment by realnc** [comment]
From the Tads banner spec:

```c
/* 
 *   Normal text stream window.  This is a text stream that behaves
 *   essentially like the main text window: text is displayed to this
 *   through os_banner_disp(), always in a stream-like fashion by adding new
 *   text to the end of any exiting text.
 *   
 *   Systems that use proportional fonts should usually simply use the same
 *   font they use by default in the main text window.  However, note that
 *   the OS_BANNER_STYLE_TAB_ALIGN style flag might imply that a fixed-pitch
 *   font should be used even when proportional fonts are available, because
 *   a fixed-pitch font will allow the calling code to rely on using spaces
 *   to align text within the window.  
 */
#define OS_BANNER_TYPE_TEXT       1
```

("Calling code" refers to game code.)

So if measuring window size in fixed-width characters violates the Glk spec, then that means there's no 1:1 mapping of the Tads banner API to Glk, so no matter what you do, there's always going to be a case where something won't look as intended.

**Comment by curiousdannii** [comment]
Thanks for the extra clarification.

I think the linked PR is okay because it basically doesn't change anything. The Glk port was already setting all styles to be fixed width, and switching to a grid window is just a more reliable way of doing that.

Now I assume it's also possible to have only some text be fixed width in a text banner, although the Glk port doesn't seem to support that currently, from what I could see. And if the width of text banners that aren't tab aligned should still be measured according to fixed width fonts, then there are a few ways we could handle getting accurate measurements. But that would be something to pursue later. I'm focusing on fixing the most obvious problems first. :)

I guess one difference would be if tab aligned windows are intended to still be scrolled when you write too much to them. If that's the case then rather than the PR it would be better to fix the banner width function.

**Comment by realnc** [comment]
> And if the width of text banners that aren't tab aligned should still be measured according to fixed width fonts, then there are a few ways we could handle getting accurate measurements.

I believe normal `OS_BANNER_TYPE_TEXT` banners don't ever want to know their own width, since they're only supposed to print text streams. Their height is important, but that's easy to do with proportional fonts, since those fonts only have variable widths, but the line-to-line distance of a font is constant. If you were to measure the height in fixed-width metrics but then print a different font, the banner would have the wrong height.
