### ISSUE TITLE
DOS to Unix line endings

### ISSUE THREAD

**Issue by realnc** [tads-intfic/tads-runner#2]
I just force-pushed a line endings conversion from DOS to Unix with rewritten git history. For some reason, the `.git` directory when cloning grew from 8MB to 20MB. Not sure what's going on with that. Otherwise, it appears to have worked.

Let's see if any git issues crop up.

**Comment by curiousdannii** [comment]
Excellent, thanks!

I know your local git working copy will keep old commits even if they're no longer in any branches, so perhaps even cloning will do that? I think Github periodically runs a cleanup process on repos, so maybe the old commits will disappear in the future and the size will go back down?
