### ISSUE TITLE
Memory error/null function

### ISSUE THREAD

**Issue by curiousdannii** [tads-intfic/tads-runner#25]
https://intfiction.org/t/detecting-emscripten-based-interpreters-at-runtime/60434

I've been investigating this error, but have reached about the limits of what I can work out.

I've narrowed it down to `local_symtab_` not being set when `CTcParser::create_sym_node` is called, but I don't know why it wouldn't be.

I wondered if the reason why the error only occurs in Emglken is because of Clang, but I compiled it with normal Clang and it worked fine. It's possible there's a Emscripten error, but it feels slightly more likely that there's an obscure bug in TADS somewhere.

Any ideas of what could be wrong, or how to further diagnose the issue?

Test case: [game.zip](https://github.com/tads-intfic/tads-runner/files/10773400/game.zip)

**Comment by realnc** [comment]
This cropped up a couple years ago (2019) when Mike Roberts was still somewhat active. Discussion from back then:

> On further investigation, what's going on is that if the preceding .t source code had a local scope from a code body (say, a method definition with parameters or local variables) as part of the grammar statement, that old local scope is being left active when we build the property symbol list.  That's wrong.  The ideal solution would probably be to carefully track down the conditions under which an old local scope can get left over like this, but that might take some doing; a much more expedient solution that will properly clear out left-over local scopes for this 'grammar' list, at least, is to explicitly set the local scope to the global scope, just before building the property symbol list.


Clearing out the left-over local scope means patching `tads3/tcprsprg.cpp` like this:

```diff
diff --git a/tads3/tcprsprg.cpp b/tads3/tcprsprg.cpp
index 6f7eceb..236c1cc 100644
--- a/tads3/tcprsprg.cpp
+++ b/tads3/tcprsprg.cpp
@@ -1623,6 +1623,9 @@ CTPNStmTop *CTcParser::parse_grammar(int *err, int replace, int modify)
         CTcConstVal cval;
         size_t i;
 
+        /* this is in global scope */
+        local_symtab_ = global_symtab_;
+
         /* create the list expression */
         lst = new CTPNList();
```

Does that fix it for you?

**Comment by curiousdannii** [comment]
That sounds promising, but tcprsprg.cpp isn't compiled into Garglk/Emglken's TADS interpreter. Maybe adding the same line somewhere else would help, but in which file/function..?
