### ISSUE TITLE
Increase the UNDO limit

### ISSUE THREAD

**Issue by curiousdannii** [tads-intfic/tads-runner#29]
The default undo limit is set in [vmparam.h](https://github.com/tads-intfic/tads-runner/blob/master/tads3/vmparam.h#L96). In [some large T3 games](https://intfiction.org/t/undo-info-in-tads-vm/61243) it only has space for two undos.

Based on the comments in vmparam.h it looks like 4096 undo records would take up 64KB of RAM. I think we could easily double that without issue. Or should we increase it even further?

**Comment by realnc** [comment]
A (long) while ago, I made it runtime configurable in FrobTADS with the default being 16 times the default (so 65536) and max savepoints hardcoded to 255 (the maximum possible.) I haven't seen any issues. So you might as well just do:

```c++
#define VM_UNDO_MAX_RECORDS  65536
#define VM_UNDO_MAX_SAVEPTS  255
```

**Comment by curiousdannii** [comment]
Thanks! That's such a big increase that it should be fine without even making it runtime configurable. That makes the runtime buffer 1MB with 32 bit pointers, and 2MB with 64 bit pointers. If that's a problem it can always be manually defined.
